os: linux
language: python
cache:
    pip: true

python:
    - "3.6"

install:
    - pip install -e .[tests]
    - pip install -r requirements.txt
    - pip install codecov

script:
    - python --version
    - coverage run -m py.test tests
    - cd docs
    - make doc
    - make html
    - touch build/html/.nojekyll  # prevents use jekyll to build doc

# Push the results back to codecov
after_success:
    - coverage report -m
    - codecov

deploy:
    provider: pages
    skip_cleanup: true
    keep_history: false
    github_token: $GITHUB_PAGES
    local_dir: docs/build/html
    on:
      branches: master
