os: linux
language: python
cache:
    pip: true

python:
    - "3.6"

install:
    - pip install -e .[tests]
    - pip install -r requirements.txt

script:
    - python --version
    - py.test
    - cd docs
    - make doc
    - make html
    - touch build/html/.nojekyll  # do not use jekyll to build doc

deploy:
    provider: pages
    skip_cleanup: true
    keep_history: false
    github_token: $GITHUB_PAGES
    local_dir: docs/build/html
    on:
      all_branches: true
