# Filterbank config
filterbank:
# n_filters: 512
# kernel_size: 512
# stride: 256
 n_filters: 256
 kernel_size: 256
 stride: 64
 log: True # Use log spectra as input
# Training config
training:
  epochs: 100
  half_lr: yes
  early_stop: yes
  max_norm: 5
  checkpoint: n
  continue_from:
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
    #  tr_wav_len_list: /srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/ssivasankaran/experiments/data/speech_separation/wsj0-mix/2speakers_reverb_kinect_chime_noise_corrected/wav16k/max/tr.wavid.sample
    #  cv_wav_len_list: /srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/ssivasankaran/experiments/data/speech_separation/wsj0-mix/2speakers_reverb_kinect_chime_noise_corrected/wav16k/max/cv.wavid.sample
    #  tt_wav_len_list: /srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/ssivasankaran/experiments/data/speech_separation/wsj0-mix/2speakers_reverb_kinect_chime_noise_corrected/wav16k/max/tt.wavid.sample.head
  tr_wav_len_list: exp/tr.wavid.samples
  cv_wav_len_list: exp/cv.wavid.samples
  tt_wav_len_list: exp/tt.wavid.samples
  wav_base_path: /srv/storage/talc3@talc-data.nancy/multispeech/calcul/users/ssivasankaran/experiments/data/speech_separation/wsj0-mix/2speakers/wav8k/min/
  #wav_base_path: /tmp/min
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 8000
  mode: max
  batch_size: 4
  num_workers: 20
  segment: 4 # Segment length in seconds for training
