data:
  sample_rate: 16000
  segment:
  train_json: ./data/train.json
  dev_json: ./data/validation.json
  test_json: ./data/test.json
  spk_dict: ./data/spk_dict.json
  n_src: 1
# net:
#   enc_dim: 64
#   chunk_size: 50
#   hop_size: 25
#   feature_dim: 64
#   hidden_dim: 128
#   n_layers: 4
#   n_src: 2
#   window_ms: 4
#   context_ms: 16
filterbank:
  n_channels: 2
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  in_chan: 1024 # 512 * n_ch
  out_chan: 1024 # 512 * n_ch
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 1024 # 512 * n_ch
optim:
  lr: 0.001
  weight_decay: !!float 1e-5
training:
  epochs: 200
  batch_size: 4
  gradient_clipping: 5
  accumulate_batches: 4 # global batch 32
  save_top_k: 10
  num_workers: 8
  patience: 10
  half_lr: true
  early_stop: true
