# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 32
  stride: 16
# Network config
masknet:
  n_blocks: 4
  n_repeats: 2
  mask_act: ReLU
# Training config
training:
  epochs: 100
  half_lr: yes
  early_stop: yes
  max_norm: 5
#
optim:
  lr: 0.001
  weight_decay: 0.
data:
  train_dir: data/2speakers_wham/wav8k/min/tr/
  valid_dir: data/2speakers_wham/wav8k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
  batch_size: 3
  num_workers: 4
